[package]
name = "ntex-files"
version = "0.1.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Static files support for ntex web."
readme = "README.md"
keywords = ["ntex", "http", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex-extras.git"
documentation = "https://docs.rs/ntex-files/"
categories = ["asynchronous", "web-programming::http-server"]
license = "MIT"
edition = "2018"
workspace = ".."

[lib]
name = "ntex_files"
path = "src/lib.rs"

[dependencies]
ntex = "0.3.5"
bitflags = "1.2"
futures = "0.3"
derive_more = "0.99.11"
hyperx = { git = "https://github.com/y0zong/hyperx.git" }
log = "0.4"
mime = "0.3"
mime_guess = "2.0.1"
percent-encoding = "2.1"
v_htmlescape = "0.13"

[dev-dependencies]
ntex = { version = "0.3.5", features = ["openssl", "compress"] }
